from pydantic import BaseModel, Field
from datetime import datetime

"""
    Structured output the LLM must return; code builds the final Answer from it

    Attributes:
        answer: str
"""
class LLMAnswer(BaseModel, frozen=True):
    answer: str = Field(description="Plain-language answer to the user, based only on tool results")


"""
    Answer schema generated by the agent

    Attributes:
        timestamp: str
        model: str
        prompt: str
        answer: str
"""
class Answer(BaseModel, frozen=True):
    timestamp: str
    model: str
    prompt: str
    answer: str


# Function to create an error answer
ERROR_ANSWER = lambda error, model, prompt: Answer(
    timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
    model=model,
        prompt=prompt,
        answer=error,
)